AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Application Load Balancer in public subnet'

Resources:
  # Security Group for the ALB
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Application Load Balancer
      VpcId: !ImportValue myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ALB-SecurityGroup

  # Application Load Balancer
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: my-application-lb
      Scheme: internet-facing
      Type: application
      SecurityGroups: 
        - !Ref ALBSecurityGroup
      Subnets: 
        - !ImportValue MyPublicSubnet1
        - !ImportValue MyPublicSubnet2
      Tags:
        - Key: Name
          Value: MyApplicationLoadBalancer

  # Target Group
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: my-alb-target-group
      Port: 80
      Protocol: HTTP
      VpcId: !ImportValue myVPC
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      TargetType: instance
      Tags:
        - Key: Name
          Value: MyALBTargetGroup

  # HTTPS Listener on 443
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !ImportValue CertificateArn

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: ALBDNSName
  
  TargetGroupArn:
    Description: ARN of the Target Group
    Value: !Ref ALBTargetGroup
    Export:
      Name: ALBTargetGroupArn

  LoadBalancerCanonicalHostedZoneID:
    Description: Canonical hosted zone ID of the load balancer
    Value: !GetAtt ApplicationLoadBalancer.CanonicalHostedZoneID
    Export:
      Name: ALBCanonicalHostedZoneID
