AWSTemplateFormatVersion: '2010-09-09'
Description: Master template for nested stacks with all resources

Parameters:
  DomainName:
    Type: String
    Description: The domain name for the application
    Default: www.mymvp.me

  BucketName:
    Type: String
    Description: Name of the S3 bucket containing CloudFormation templates
    Default: cf-bucket-123434

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/${AWS::Region}/network.yml

  CertificateStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/${AWS::Region}/certificate.yml
      Parameters:
        DomainName: !Ref DomainName

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CertificateStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/${AWS::Region}/loadbalancer.yml

  ApplicationStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: LoadBalancerStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/${AWS::Region}/ec2.yml

  DNSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - LoadBalancerStack
      - CertificateStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/${AWS::Region}/dns.yml
      Parameters:
        ApplicationDomainName: !Ref DomainName

Outputs:
  DomainEndpoint:
    Description: Domain endpoint for the application
    Value: !GetAtt DNSStack.Outputs.DomainEndpoint
  
  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt LoadBalancerStack.Outputs.LoadBalancerDNS
  
  CertificateArn:
    Description: ARN of the SSL/TLS certificate
    Value: !GetAtt CertificateStack.Outputs.CertificateArn
    
  DomainName:
    Description: Domain name for the application
    Value: !Ref DomainName
