# test whether this works connect to the ec2 instance

# Network template:
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.8.0/22
      Tags:
        - Key: Name
          Value: vpc271124
  MyPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.8.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: public
  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.9.0/24
      Tags:
        - Key: Name
          Value: private

  # Add an Internet Gateway
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: vpc271124

  # Attach Internet Gateway to VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref MyInternetGateway

  # Create a Route Table for Public Subnet
  MyPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: vpc271124

  # Create a Route in the Public Route Table for Internet Access
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref MyPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref MyInternetGateway

  # Associate the Route Table with the Subnet
  MySubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref MyPublicSubnet
      RouteTableId: !Ref MyPublicRouteTable

Outputs:
  MyPrivateSubnetExport:
    Value: !Ref MyPrivateSubnet
    Export:
      Name: MyPrivateSubnetCICD
  MyPublicSubnetExport:
    Value: !Ref MyPublicSubnet
    Export:
      Name: MyPublicSubnetCICD
  MyVPCExport:
    Value: !Ref myVPC
    Export:
      Name: myVPCCICD
