 vpc endpoints with security

#Resources:
# MyInstance:
# This  is not a working example:    Type: AWS::EC2::Instance
#    Properties:
#      InstanceId: !ImportValue MyInstance
#      IamInstanceProfile: !ImportValue  MyInstanceProfile  # Optional: Add an instance profile

# security group has to open 443
Resources:
  AddInboundRule2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !ImportValue SecurityGroup
      IpProtocol: tcp
      FromPort: 443
      ToPort: 443
      CidrIp: 0.0.0.0/0

  # add role
  EC2SSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2SSMRole # Optional, customize or omit to auto-generate
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2SSMInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: EC2SSMInstanceProfile # Optional, customize or omit
      Roles:
        - !Ref EC2SSMRole


Outputs:
  InstanceProfile:
    Description: Instance Profile
    Value: !Ref EC2SSMInstanceProfile
    Export:
      Name: MyInstanceProfile
