AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create a Launch Template

Parameters:
  VpcId:
    Description: The VPC ID where the resources will be created
    Type: String
    Default: vpc-070ea2628067caf4a

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-0c55b159cbfafe1f0
        KeyName: my-key-pair
        SecurityGroupIds:
          - !Ref MySecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: MyLaunchTemplateInstance
