AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for SSL/TLS Certificate configuration

Parameters:
  DomainName:
    Type: String
    Description: The domain name for the application (e.g., example.com)
  
  HostedZoneId:
    Type: AWS::Route53::HostedZone::Id
    Description: The Route 53 Hosted Zone ID for the domain

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub www.${DomainName}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub www.${DomainName}
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-certificate

Outputs:
  CertificateArn:
    Description: ARN of the SSL/TLS certificate
    Value: !Ref Certificate
    Export:
      Name: !Sub ${AWS::StackName}-CertificateArn
