AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance in a non-default VPC.

Parameters:
  VpcId:
    Description: The ID of the non-default VPC
    Type: AWS::EC2::VPC::Id

  SubnetId:
    Description: The Subnet ID within the specified VPC
    Type: AWS::EC2::Subnet::Id

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: Must be a valid EC2 instance type.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      ImageId: ami-0453ec754f44f9a4a # Example: Amazon Linux 2 AMI (ensure correct region)
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access within the specified VPC
      VpcId: !Ref VpcId

Outputs:
  InstanceId:
    Description: ID of the EC2 instance
    Value: !Ref EC2Instance
    Export:
      Name: MyInstance
  SecurityGroup:
    Description: Security group
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: SecurityGroup
